apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stack.backend.fullname" . }}
  labels:
    {{- include "stack.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stack.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stack.backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "stack.serviceAccountName" . }}

      containers:
        - name: backend
          image: {{ include "stack.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: backend
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP

          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "stack-stack-postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "mydb"
            - name: DATABASE_USERNAME
              value: "admin"
            - name: DATABASE_PASSWORD
              value: "admin"
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_SSL_REJECT_UNAUTHORIZED
              value: "false"

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
