apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stack.frontend.fullname" . }}
  labels:
    {{- include "stack.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stack.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stack.frontend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "stack.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "stack.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: HOST
              value: {{ .Values.frontend.env.HOST | quote }}
            - name: PORT
              value: {{ .Values.frontend.env.PORT | quote }}
          ports:
            - name: frontend
              containerPort: {{ .Values.frontend.env.PORT }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
