apiVersion: v1
kind: Service
metadata:
  name: {{ include "stack.frontend.fullname" . }}
  labels:
    {{- include "stack.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}  # LoadBalancer
  selector:
    {{- include "stack.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: frontend
      port: 80             # External/public port
      targetPort: 3000     # Container port Strapi listens on
      protocol: TCP
